# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10df1e555795849e1ee9c1d2813978e1232db462c9903e4346eeb6c400ca377c564ecad9c581edf4cb2ec67eac9082f3bc11c7f072864800dcc796a6638aa60d

test:
  secret_key_base: 4a8f18931c426b49c5fd17554a27352efb1123818bed1d635ebf7e5f35f87e90afa6e87f5609625f74463c8cfd3157fa9695a775f662d5e8c2854a6632ba9554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
